name: Create Version

on:
  push:
    branches:
      - main  # 你希望触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  calculate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # 设置所需的 Go 版本

      - name: Calculate version
        id: calculate_version
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "Running version calculation for automatic triggers"
            go run -v ./cmd/internal/read_tag --ci --nightly
          else
            echo "Running version calculation for manual triggers"
            go run -v ./cmd/internal/read_tag --ci
          fi

      - name: Output version
        run: |
          echo "The calculated version is ${{ steps.calculate_version.outputs.version }}"
